# Generated by Django 2.2.1 on 2019-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0002_auto_20190506_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodent',
            name='background_other',
            field=models.CharField(blank=True, max_length=20, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='genotype_other',
            field=models.CharField(blank=True, max_length=20, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='model_type_other',
            field=models.CharField(blank=True, max_length=20, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
