# Generated by Django 2.1.8 on 2019-06-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0004_rodent_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodent',
            options={'verbose_name_plural': 'rodents'},
        ),
    ]
