# Generated by Django 2.1.8 on 2019-06-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0005_auto_20190610_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodent',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='model_type_other',
        ),
    ]
