# Generated by Django 2.1.8 on 2019-06-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodent',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rodents', to='rodentdb.Category'),
            preserve_default=False,
        ),
    ]
