# Generated by Django 2.1.8 on 2019-06-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0008_rodent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodent',
            name='background',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='background_other',
        ),
    ]
