# Generated by Django 2.1.8 on 2019-06-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0011_rodent_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodent',
            name='genotype',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='genotype_other',
        ),
    ]
