# Generated by Django 2.1.8 on 2019-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0012_auto_20190611_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'genotype',
                'verbose_name_plural': 'genotypes',
                'ordering': ['name'],
            },
        ),
    ]
