# Generated by Django 2.1.8 on 2019-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0017_rodent_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodent',
            name='line_description',
            field=models.TextField(blank=True),
        ),
    ]
