# Generated by Django 2.1.8 on 2019-06-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0019_rodent_maintainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodent',
            name='lab',
        ),
    ]
