# Generated by Django 2.1.8 on 2019-06-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('rodentdb', '0020_remove_rodent_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodent',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
