# Generated by Django 2.1.8 on 2019-06-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0023_coatcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodent',
            name='coat_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodentdb.CoatColor'),
        ),
    ]
