# Generated by Django 2.1.8 on 2019-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0024_rodent_coat_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'reporter gene',
                'verbose_name_plural': 'reporter genes',
                'ordering': ['name'],
            },
        ),
    ]
