# Generated by Django 2.1.8 on 2019-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0026_rodent_reporter_gene'),
    ]

    operations = [
        migrations.CreateModel(
            name='InducibleCassette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'inducible cassette',
                'verbose_name_plural': 'inducible cassettes',
                'ordering': ['name'],
            },
        ),
    ]
