# Generated by Django 2.1.8 on 2019-06-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0027_induciblecassette'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodent',
            name='inducible_cassette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodentdb.InducibleCassette'),
        ),
    ]
