# Generated by Django 2.1.8 on 2019-06-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0028_rodent_inducible_cassette'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genotype',
            new_name='Zygosity',
        ),
        migrations.AlterModelOptions(
            name='zygosity',
            options={'ordering': ['name'], 'verbose_name': 'zygosity', 'verbose_name_plural': 'zygosities'},
        ),
        migrations.RenameField(
            model_name='rodent',
            old_name='genotype',
            new_name='zygosity',
        ),
    ]
