# Generated by Django 2.1.8 on 2019-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0029_auto_20190621_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zygosity',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
