# Generated by Django 2.1.8 on 2019-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0031_auto_20190621_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodent',
            name='zygosity',
        ),
        migrations.AddField(
            model_name='rodent',
            name='zygosity',
            field=models.ManyToManyField(blank=True, related_name='rodents', to='rodentdb.Zygosity'),
        ),
    ]
