# Generated by Django 2.1.8 on 2019-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0032_auto_20190621_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodent',
            name='origin',
        ),
        migrations.AddField(
            model_name='rodent',
            name='origin_other',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
