# Generated by Django 2.1.8 on 2019-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0033_auto_20190621_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'origin',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
    ]
