# Generated by Django 2.1.8 on 2019-06-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0034_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodent',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rodents', to='rodentdb.Origin'),
        ),
    ]
