# Generated by Django 2.1.8 on 2019-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0035_rodent_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origin',
            options={'ordering': ['name'], 'verbose_name': 'origin', 'verbose_name_plural': 'origins'},
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
