# Generated by Django 2.1.8 on 2019-06-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0036_auto_20190621_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodent',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rodents', to='rodentdb.Origin'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='origin_other',
            field=models.CharField(blank=True, max_length=40, verbose_name='origin'),
        ),
    ]
