# Generated by Django 2.1.11 on 2019-08-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodentdb', '0039_auto_20190813_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodent',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Group'),
        ),
    ]
